server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: management
          uri: http://localhost:8081
          predicates:
            - Path=/managements/** 
        - id: rental
          uri: http://localhost:8082
          predicates:
            - Path=/rents/** 
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/pays/** 
        - id: customerCenter
          uri: http://localhost:8084
          predicates:
            - Path= /customerCenters/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/managements/** 
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rents/** 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/** 
        - id: customerCenter
          uri: http://customerCenter:8080
          predicates:
            - Path= /customerCenters/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080